version: '2'
services:
    caixa-app:
        image: caixa
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://caixa-postgresql:5432/Caixa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    caixa-postgresql:
        extends:
            file: postgresql.yml
            service: caixa-postgresql
