version: '2'
services:
    caixa-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/Caixa/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Caixa
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
